config = {
    "version": "1",
    "dir_geotiff": "./output/geotiff",
    "dir_staged": "./output/staged",
    "dir_web_tiles": "./output/web_tiles",
    "dir_input": "input",
    "dir_3dtiles": "./output/3dtiles",
    "filename_staging_summary": "./output/staging_summary_4326.csv",
    "filename_rasterization_events": "./output/rasterization_events.csv",
    "filename_rasters_summary": "./output/rasters_summary.csv",
    "filename_config": "config.py",
    "ext_input": ".gpkg",
    "ext_staged": ".gpkg",
    "overwrite": True,
    "prop_area": "staging_area",
    "prop_tile": "staging_tile",
    "prop_filename": "staging_filename",
    "prop_identifier": "staging_identifier",
    "input_crs": None,
    "simplify_tolerance": 0.0001,
    "tms_id": "WGS1984Quad",
    "tile_path_structure": ["style", "tms", "z", "x", "y"],
    "z_range": [0, 2],
    "tile_size": [256, 256],
    "clip_to_footprint": False,
    "statistics": [
        {
            "name": "polygon_count",
            "weight_by": "count",
            "property": "centroids_per_pixel",
            "aggregation_method": "sum",
            "resampling_method": "sum",
            "val_range": [0, None],
            "nodata_val": 0,
            "nodata_color": "#ffffff00",
            "palette": [
                "#FAE9E5",
                "#EBA7A1",
                "#DB6F6B",
                "#BB3B39",
                "#8F1819",
            ]
        },
        {
            "name": "coverage",
            "weight_by": "area",
            "property": "area_m2",
            "aggregation_method": "sum",
            "resampling_method": "average",
            "nodata_val": 0,
            "nodata_color": "#ffffff00",
            "val_range": [288,636962],
            "palette": [
                "#FAE9E5",
                "#EBA7A1",
                "#DB6F6B",
                "#BB3B39",
                "#8F1819",
            ]
        }
    ],
    "enable_stager": True,
    "enable_raster": True,
    "enable_3dtiles": False
}
